[tool.poetry]
name = "module2"
version = "0.1.0"
description = ""
authors = ["5x12 <contact@awolf.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.7"
scikit-learn = "^1.3.1"
pandas = "^2.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
