# This is our first Github Actions workflow!

name: Build Application

runs:
  using: composite

  steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Set up Python 3.10.7
    uses: actions/setup-python@v5
    with:
      python-version: '3.10.7'

  - name: Install poetry
    uses: snok/install-poetry@v1
    with:
      virtualenvs-in-project: true
    
  - name: Load cached venv
    uses: actions/cache@v4
    id: cached-poetry-dependencies
    with:
      path: .venv
      key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

  - name: Install dependencies using poetry
    if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
    run: poetry run make install
    shell: bash
