[DATA]
data_set = "https://raw.githubusercontent.com/5x12/ml-cookbook/master/supplements/data/heart.csv"
target_name = 'target'
x_test = "model/test_sets/x_test_heart.pkl"
y_test = "model/test_sets/y_test_heart.pkl"
kn_y_preds = "model/preds/kn_y_preds_heart.pkl"
xgb_y_preds = "model/preds/xgb_y_preds_heart.pkl"

[REPORTS]
kn_report = "model/reports/kn_report_{timestamp}.txt"
xgb_report = "model/reports/xgb_report_{timestamp}.txt"

[PREPROCESSOR]
prep_conf = "model/conf/preprocessor_heart.pkl"

[MODEL]
kn_conf = "model/conf/kneighbors_heart.pkl"
xgb_conf = "model/conf/xgboost_heart.pkl"

[SPLITTING]
parameters_splitting = {'random_state' = 42, 'test_size' = 0.3}

[CROSS_VALIDATION_PARAMS]
parameters_cv = {'n_splits' = 5, 'shuffle' = true}

[GRID_SEARCH_PARAMS]
parameters_kn = {'param_grid' = {'regressor__n_neighbors' = [5, 7, 9, 11, 13, 15, 17, 19, 21]}, 'scoring' = 'accuracy'}
parameters_xgb = {'param_grid' = {'regressor__learning_rate' = [0.001, 0.005, 0.01, 0.015, 0.02], 'regressor__n_estimators' = [20, 25, 30, 35, 40], 'regressor__max_depth' = [5, 10, 15, 20], 'regressor__gamma' = [0.2, 0.4, 0.6, 0.8], 'regressor__seed' = [27]}, 'scoring' = 'accuracy'}

[CATEGORICAL]
cat_features = ['cp', 'slope', 'thal']

[NUMERIC]
num_features = ['age', 'sex', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'ca']